In [33]:
import numpy as np

In [34]:
arr = np.array([12,23,45,56,32])

In [35]:
arr

array([12, 23, 45, 56, 32])

In [36]:
print(arr)

[12 23 45 56 32]


In [37]:
type(arr)

numpy.ndarray

In [38]:
arr.dtype

dtype('int32')

In [39]:
%%timeit
arr = np.array([12,23,34,45,56.88,'Swarali'])

7.95 µs ± 1.03 µs per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [32]:
arr

array([12, 23, 45, 56, 32])

In [40]:
arr.dtype

dtype('int32')

In [41]:
%%timeit
arr=np.array([12,23,34,45,56.88,'Swarali'])

6.71 µs ± 568 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [42]:
arr[3]

56

In [43]:
arr.shape

(5,)

In [44]:
arr = np.array([12,23,34,45,56.88])

In [45]:
arr*2

array([ 24.  ,  46.  ,  68.  ,  90.  , 113.76])

In [48]:
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [49]:
np.arange(2,20)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [50]:
np.arange(-5,5,0.5)

array([-5. , -4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,
        0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])

In [51]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [52]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [53]:
# 2d

In [54]:
arr1=np.array([[1,2,3],[5,6,7],[9,9,0]])

In [55]:
arr1

array([[1, 2, 3],
       [5, 6, 7],
       [9, 9, 0]])

In [56]:
arr1.shape

(3, 3)

In [57]:
arr1.ndim

2

In [59]:
arr1.flatten()

array([1, 2, 3, 5, 6, 7, 9, 9, 0])

In [62]:
arr1.reshape(3,-1,2)

ValueError: cannot reshape array of size 9 into shape (3,newaxis,2)

In [63]:
arr1[0:3,0:2]

array([[1, 2],
       [5, 6],
       [9, 9]])

In [64]:
arr

array([12.  , 23.  , 34.  , 45.  , 56.88])

In [65]:
arr.mean()

34.176

In [66]:
arr.min()

12.0

In [67]:
np.unique(arr)

array([12.  , 23.  , 34.  , 45.  , 56.88])

In [68]:
np.linalg.det(arr)

LinAlgError: 1-dimensional array given. Array must be at least two-dimensional